name: Build EPUB

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Rust 工具链（mdbook-epub 依赖 Rust）
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 4. 安装 mdbook-epub
      - name: Install mdbook-epub
        run: cargo install mdbook-epub

      # 5. 构建 EPUB
      - name: Build EPUB
        run: |
          mdbook-epub --standalone true

      # 6. 上传生成的 EPUB 文件作为构建产物
      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v3
        with:
          name: book.epub
          path: book/epub/book.epub  # mdbook-epub 默认输出路径
